### ISSUE TITLE
IndexError when there is a header but no {@CONTENT} in file

### ISSUE THREAD

**Issue by PariahVi** [PariahVi/ignis#1]
Here is the error message.

    Traceback (most recent call last):
      File "/usr/bin/ignis", line 650, in <module>
        main()
      File "/usr/bin/ignis", line 640, in main
        handle_files(get_files(), verbose, mock_flag)
      File "/usr/bin/ignis", line 213, in handle_files
        header_vars, is_header = get_header(f, input_content)
      File "/usr/bin/ignis", line 462, in get_header
        while content[0] == ord(b"\n"):
    IndexError: index out of range

**Comment by PariahVi** [comment]
fixed in fee6c28.
